name: Terraform Provisioning  

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.5

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform changes
      run: terraform apply -auto-approve

    - name: Upload files to EC2 instance
      run: |
        scp -i ${{ secrets.AWS_SECRET_ACCESS_KEY }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null setup.sh ec2-user@13.235.86.121:/tmp/
        scp -i ${{ secrets.AWS_SECRET_ACCESS_KEY }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null kong.yaml ec2-user@13.235.86.121:/tmp/

    - name: Run setup.sh script remotely
      run: ssh -i ${{ secrets.AWS_SECRET_ACCESS_KEY }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@13.235.86.121 "chmod +x /tmp/setup.sh && /tmp/setup.sh"
